name: Test and build the mod package

on:
  push:
    branches: ['**']
    # Do not run on release creation
    tags-ignore:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - 'docker/**'
    - '.github/workflows/docker-image-workflow.yml'
  pull_request:
    paths-ignore:
    - 'docker/**'
    - '.github/workflows/docker-image-workflow.yml'

env:
  IMAGE_NAME: jhakonen/tessumod:mod-builder-latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout sources and get plugin version string from latest tag
    - uses: actions/checkout@v2

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Pull docker image from Docker Hub
      shell: bash
      run: |
        echo "Pull docker image: $IMAGE_NAME"
        docker pull $IMAGE_NAME

    - name: Run unit tests
      shell: bash
      run: |
        docker run \
          --rm \
          --volume '${{ github.workspace }}:/build' \
          $IMAGE_NAME \
          python3 setup.py test

    - name: Run fute tests
      shell: bash
      run: |
        docker run \
          --rm \
          --volume '${{ github.workspace }}:/build' \
          $IMAGE_NAME \
          python3 setup.py fute

    - name: Build release package
      id: package
      shell: bash
      run: |
        docker run \
          --rm \
          --volume '${{ github.workspace }}:/build' \
          $IMAGE_NAME \
          python3 setup.py clean package

    - name: Upload mod release package artifact
      uses: actions/upload-artifact@v1
      with:
        name: release-package
        path: ${{ steps.package.outputs.release-package }}
